const  Posts = [
  {
    _createdAt: new Date(),
    views: 100,
    author: { _id: 1, name: "John Doe" },
    _id: 2,
    description: "A dummy description",
    title: "Project's Title",
    image: "https://fakeimg.pl/600x500",
    category: "Technology",
  },
  {
    _createdAt: new Date(),
    views: 150,
    author: { _id: 2, name: "Jane Smith" },
    _id: 3,
    description: "A description for the second project",
    title: "Second Project",
    image: "https://fakeimg.pl/600x500",
    category: "Science",
  },
  {
    _createdAt: new Date(),
    views: 250,
    author: { _id: 3, name: "Alice Brown" },
    _id: 4,
    description: "A short description for project three",
    title: "Third Project",
    image: "https://fakeimg.pl/600x500",
    category: "Engineering",
  },
  {
    _createdAt: new Date(),
    views: 180,
    author: { _id: 4, name: "Bob White" },
    _id: 5,
    description: "Project four's description goes here",
    title: "Fourth Project",
    image: "https://fakeimg.pl/600x500",
    category: "Mathematics",
  },
  {
    _createdAt: new Date(),
    views: 300,
    author: { _id: 5, name: "Chris Black" },
    _id: 6,
    description: "Description for project five",
    title: "Fifth Project",
    image: "https://fakeimg.pl/600x500",
    category: "Technology",
  },
  {
    _createdAt: new Date(),
    views: 220,
    author: { _id: 6, name: "Eve Johnson" },
    _id: 7,
    description: "An overview of project six",
    title: "Sixth Project",
    image: "https://fakeimg.pl/600x500",
    category: "Arts",
  },
  {
    _createdAt: new Date(),
    views: 175,
    author: { _id: 7, name: "Frank Brown" },
    _id: 8,
    description: "Brief description for project seven",
    title: "Seventh Project",
    image: "https://fakeimg.pl/600x500",
    category: "Technology",
  },
  {
    _createdAt: new Date(),
    views: 210,
    author: { _id: 8, name: "Grace Green" },
    _id: 9,
    description: "A look at project eight",
    title: "Eighth Project",
    image: "https://fakeimg.pl/600x500",
    category: "History",
  },
  {
    _createdAt: new Date(),
    views: 195,
    author: { _id: 9, name: "Hank Pink" },
    _id: 10,
    description: "Short info on project nine",
    title: "Ninth Project",
    image: "https://fakeimg.pl/600x500",
    category: "Technology",
  },
  {
    _createdAt: new Date(),
    views: 310,
    author: { _id: 10, name: "Ivy Blue" },
    _id: 11,
    description: "Description for the tenth project",
    title: "Tenth Project",
    image: "https://fakeimg.pl/600x500",
    category: "Medicine",
  },
];

export default Posts;
